### ISSUE TITLE
Cache Servers

### ISSUE THREAD

**Issue by vmitchell85** [KevinBatdorf/laravel-forge-raycast#1]
I noticed you weren't sure if you should cache Servers... (permalink below) I cached sites _and servers_ in Alforge (my Alfred workflow) and I think it made it work much better.

https://github.com/KevinBatdorf/laravel-forge-raycast/blob/6b7ee63de856d204dfb30ffa22a7e24953952bf6/src/Server.tsx#L18

**Comment by vmitchell85** [comment]
Might be worth enabling discussions too, so you can see what sort of features people would like.

**Comment by KevinBatdorf** [comment]
Yeah I wasn't sure because I want to ping the api every 2-3 seconds regardless, but there's a slight flash before the data shows, so I probably will cache them. Will check out how Raycast handles caching.

> Might be worth enabling discussions too, so you can see what sort of features people would like.

Thanks, just enabled them. Thanks for the tip.
