### ISSUE TITLE
iTerm2

### ISSUE THREAD

**Issue by plakhin** [KevinBatdorf/laravel-forge-raycast#12]
Is it possible to use iTerm2 instead of Terminal when opening SSH?

**Comment by KevinBatdorf** [comment]
It should just open the default terminal. For me it opens iTerm2. Type `ssh://forge@yoursite.com` in the browser and see what opens. 

Have you tried setting it as default? I think you have to do it here:

![Screen Shot 2022-08-26 at 12 04 25 AM](https://user-images.githubusercontent.com/1478421/186817721-7d4b4d4b-21e6-4927-ab3b-a340298a23f6.png)

**Comment by plakhin** [comment]
> Have you tried setting it as default? I think you have to do it here:

Yes, that is exactly what I did. 

Thank you for the response, will dig my local settings then, might be something wrong there.

**Comment by plakhin** [comment]
This helped https://ma.ttias.be/set-iterm2-default-ssh-handler-mac-osx/
